"""Turns the crew's validated handoffs into files the Godot project and the creator use.

Outputs (in the chosen output folder):
  return_crossing.json   game data loaded by godot/crossing_loader.gd
  handoffs/01..04_*.json each agent's raw validated handoff (traceability)
  HANDOFF.md             task note in the AI Agent Strategy's fixed format
  REPORT.md              orchestrator report in the fixed format
"""
import json
from datetime import datetime, timezone
from pathlib import Path

from validators import check_brief, check_calls, check_forecast, check_review


def final_checks(state: dict) -> list[str]:
    """Re-run every contract check end to end before writing game data."""
    missing = [k for k in ("brief", "forecast", "calls", "review") if k not in state]
    if missing:
        return [f"Pipeline incomplete, missing handoffs: {missing}"]
    b, f, c, r = state["brief"], state["forecast"], state["calls"], state["review"]
    return check_brief(b) + check_forecast(f, b) + check_calls(c, f, b) + check_review(r)


def build_game_data(state: dict) -> dict:
    b, f, c = state["brief"], state["forecast"], state["calls"]
    calls = {x.target_segment_id: x for x in c.calls}
    brief_segs = {s.segment_id: s for s in b.segments}
    segments, start = [], 0
    for seg in f.segments:
        sb, call = brief_segs[seg.segment_id], calls[seg.segment_id]
        segments.append({
            "segment_id": seg.segment_id,
            "start_m": start,
            "length_m": sb.length_m,
            "hazard_density": sb.hazard_density,
            "route_width_m": sb.route_width_m,
            "min_visibility_m": sb.min_visibility_m,
            "safe_lane": seg.safe_lane,
            "safe_point_id": seg.safe_point_id,
            "hazards": [h.model_dump() | {"route_m": start + h.distance_m} for h in seg.hazards],
            "jeff_call": call.model_dump() | {"trigger_route_m": max(0, start - call.lead_m)},
        })
        start += sb.length_m
    return {
        "game": "Lighting the Storm",
        "phase": "RETURN",
        "generated_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "difficulty_preset": b.difficulty_preset,
        "tuning": {"boat_speed_mps": b.boat_speed_mps, "jeff_call_lead_m": b.jeff_call_lead_m,
                   "route_length_m": start, "waves_enabled": False},
        "dock_zone_id": f.dock_zone_id,
        "events": ["RETURN_DEPARTED", "SEGMENT_ENTERED", "HAZARD_COLLISION", "RECOVERY", "RETURN_ARRIVED"],
        "segments": segments,
        "arrival_line": {"speaker": "JEFF", "line": c.arrival_line, "event": "RETURN_ARRIVED"},
    }


def write_outputs(state: dict, out_dir: str, mode: str) -> tuple[Path, list[str]]:
    out = Path(out_dir)
    (out / "handoffs").mkdir(parents=True, exist_ok=True)
    problems = final_checks(state)

    for i, key in enumerate(("brief", "forecast", "calls", "review"), 1):
        if key in state:
            (out / "handoffs" / f"0{i}_{key}.json").write_text(state[key].model_dump_json(indent=2))

    if problems:
        (out / "REPORT.md").write_text("# REPORT\n\nPipeline blocked:\n" + "\n".join(f"- {p}" for p in problems))
        return out, problems

    data = build_game_data(state)
    (out / "return_crossing.json").write_text(json.dumps(data, indent=2))
    r = state["review"]
    n_hz = sum(len(s["hazards"]) for s in data["segments"])
    checks = "\n".join(f"- [{c.result.upper()}] {c.check}: {c.evidence}"
                       for c in r.pillar_checks + r.decisions_log_checks)
    decisions = "\n".join(f"- {d}" for d in r.open_creator_decisions) or "- None"

    (out / "HANDOFF.md").write_text(f"""# HANDOFF - GATE1_RETURN_CROSSING

## 1. Task and goal
Generate Gate 1 return-crossing data for Lighting the Storm: segment tuning, hazard forecast with one safe-route signal per segment, and Jeff's direction calls that read from the same signal.

## 2. Files changed
- `return_crossing.json` (game data, stable IDs)
- `handoffs/01_brief.json`, `02_forecast.json`, `03_calls.json`, `04_review.json`

## 3. How to run and test
- Godot 4: copy `return_crossing.json` to `res://data/` and attach `godot/crossing_loader.gd` to the sea scene.
- Regenerate: `python main.py {'--offline ' if mode == 'offline' else ''}--preset {data['difficulty_preset']}`

## 4. Observed behaviour
{r.handoff_summary}
{len(data['segments'])} segments, {n_hz} hazards, route length {data['tuning']['route_length_m']} m. All deterministic contract checks passed (run mode: {mode}).

{checks}

## 5. Not verified
- Steering feel and hazard readability in engine (needs creator playtest at Gate 0/1).
- Deadline pacing against this route length.

## 6. Licences and provenance
Text and data generated by the Storm Crossing Crew; no external assets.

## 7. Interface or contract changes proposed
None. Uses the stable IDs and events from the Technical Strategy.

## 8. Open creator decisions
{decisions}
""")
    (out / "REPORT.md").write_text(f"""# REPORT - GATE1_RETURN_CROSSING

**What was delegated:** brief (Production Orchestrator), hazard forecast (Hazard Forecast Designer), Jeff calls (Companion Dialogue Writer), canon review (Canon and Review Orchestrator).

**What came back:** {len(data['segments'])} segments, {n_hz} hazards, {len(data['segments'])} Jeff calls, review verdict {r.verdict}.

**What passed review:** all {len(r.pillar_checks) + len(r.decisions_log_checks)} pillar and Decisions-log checks; all deterministic contract checks.

**What failed and why:** {'; '.join(r.issues) or 'Nothing in the final output (guardrail retries during the run are shown in the console log).'}

**What remains:** creator playtest of steering feel, readability and pacing; voice approval for Jeff's lines.

**Creator decisions that are blocking:**
{decisions}
""")
    return out, []
